#!/bin/bash
better_dir_top=$(echo "$DIR_TOP" | sed 's/\//\\\//g')
echo "#!/usr/bin/sed -f" > $DIR_TOP/.sed.temp
echo "s/__DIR_TOP__/$better_dir_top/" >> $DIR_TOP/.sed.temp
echo "s/__SECURE_WEBSITE__/$SECURE_WEBSITE/" >> $DIR_TOP/.sed.temp
echo "s/__SECURE_SERVER__/$SECURE_SERVER/" >> $DIR_TOP/.sed.temp
echo "s/__WEBSITE_NAME__/$WEBSITE_NAME/" >> $DIR_TOP/.sed.temp
echo "s/__SERVER_NAME__/$SERVER_NAME/" >> $DIR_TOP/.sed.temp
echo "s/__SECURE_WEBSITE_CHAR__/$SECURE_WEBSITE_CHAR/" >> $DIR_TOP/.sed.temp
echo "s/__SECURE_SERVER_CHAR__/$SECURE_SERVER_CHAR/" >> $DIR_TOP/.sed.temp
chmod u+x $DIR_TOP/.sed.temp
result=$(find $DIR_TOP -name "in.*" -not -path "$DIR_TOP/.git/*")
for file in $result
do
  my_dirname=$(dirname $file)/
  my_basename=$(basename $file)
  my_filename=${my_basename:3}
  $DIR_TOP/.sed.temp $file > "${my_dirname}${my_filename}"
done
rm -f $DIR_TOP/.sed.temp
